# Generated by Django 3.2.8 on 2021-10-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBOSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField()),
                ('away_team', models.CharField(max_length=100)),
                ('away_team_score', models.IntegerField(max_length=10)),
                ('home_team', models.CharField(max_length=100)),
                ('home_team_score', models.IntegerField(max_length=10)),
                ('stadium', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=2)),
                ('note', models.CharField(max_length=1000)),
            ],
        ),
    ]
