FROM python:3

ADD  requirements.txt ${HOME}
ADD  devops/jenkins/pip.conf ${HOME}/.pip/

USER root

ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 

RUN  pip install -r requirements.txt
